version: '3.8'

services:
  app:
    image: laravelphp/php-fpm
    container_name: inventory_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: inventory_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_pass
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: